### ISSUE TITLE
Markup immediately before =cut crashes Emacs (eats all RAM)

### ISSUE THREAD

**Issue by HaraldJoerg** [tree-sitter-perl/tree-sitter-pod#2]
This probably isn't an issue of tree-sitter-pod, but I'd like to narrow it down.
If I open a file with the following two lines in Emacs and parse it with tree-sitter, it eats all RAM and then gets killed.
```perl
C<
=cut
```
This is invalid POD, but it "just happens" when I type any markup immediately before the line containing `=cut`.
The same incomplete markup causes no problem when there's an empty line before `=cut`:

```perl
C<

=cut
```
...In Emacs, this gives the parse result of `(ERROR (sequence_letter) (cut_directive))`, which seems fine.

Could somebody please try the same invalid POD in neovim to narrow down whether the culprit is on the side of Emacs or on the side of Tree-sitter?  Or alternatively tell me what I'm supposed to do with the neovim snippet at https://github.com/tree-sitter-perl/tree-sitter-perl?

**Comment by rabbiveesh** [comment]
Thanks so much for this test case!
I can confirm that it loops infinitely even using the tree-sitter command line (`tree-sitter parse $filename` in the repo).

Will dig into this

**Comment by rabbiveesh** [comment]
@HaraldJoerg I just pushed a PR that should fix this. Can you try out that branch and confirm?

**Comment by HaraldJoerg** [comment]
Thanks for the fix!  I applied your PR ... and it works fine!
I forked the repository so that I could push a "release" branch containing `src/parser.c` and re-installed it using the Emacs procedure.
(Also, I should have thought of the tree-sitter command line)
