### ISSUE TITLE
B<1> is parsed as markup in a verbatim paragraph

### ISSUE THREAD

**Issue by HaraldJoerg** [tree-sitter-perl/tree-sitter-pod#4]
In a verbatim paragraph (i.e. one starting with one or more spaces) I would expect that markup is ignored - but it isn't.  The screenshot shows the resulting syntax highlighting and parse result in Emacs.
![markup_in_verbatim](https://user-images.githubusercontent.com/32883055/220866483-8bcd80a0-9f35-4948-9ec5-0ecdbbea727c.png)

**Comment by rabbiveesh** [comment]
latest commit on #3 improves this; but I think it's still not quite correct.

Behavior as implemented won't end the verbatim-ness until there's a double newline. Is that correct to spec? I think it's easier to ask than look b/c I'm not actually so fluent in POD

**Comment by HaraldJoerg** [comment]
With that patch applied it works as I'd expect it.  I don't even observe a need for a double newline if the next line is a valid POD command.  Per spec, an empty line is needed to separate paragraphs, and other parsers like pod2html will not end verbatim if the next line has a POD command without leading spaces.
Nitpick: Your parser doesn't require a space between `=head1` and `NAME`
